# Generated by Django 5.2.6 on 2025-09-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_profilemodel_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilemodel',
            old_name='account_id',
            new_name='account',
        ),
    ]
