# Generated by Django 5.2.6 on 2025-09-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=40)),
                ('Summary', models.TextField(default='')),
                ('Content', models.TextField()),
            ],
        ),
    ]
