# Generated by Django 5.2.6 on 2025-09-05 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='PostsModel',
        ),
    ]
