# Generated by Django 5.2.6 on 2025-09-06 07:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_rename_posts_postsmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
