# Generated by Django 5.2.6 on 2025-09-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0003_postsmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
