# Generated by Django 5.2.6 on 2025-09-06 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0004_alter_postsmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='JustDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
