# Generated by Django 5.2.6 on 2025-09-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homepage', '0005_postsmodel_justdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('JustDate', models.DateTimeField(auto_now_add=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Title', models.CharField(max_length=30)),
                ('Content_p1', models.CharField(max_length=700)),
                ('Content_p2', models.CharField(max_length=700)),
                ('Content_p3', models.CharField(max_length=700)),
                ('Content_p4', models.CharField(max_length=700)),
            ],
        ),
    ]
