# Generated by Django 5.2.6 on 2025-09-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_documentations'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Documentations',
        ),
    ]
