# Generated by Django 5.2.6 on 2025-09-10 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=300)),
                ('time', models.DateTimeField(default=datetime.datetime(2025, 9, 10, 20, 40, 6, 45828))),
            ],
        ),
    ]
