# Generated by Django 5.2.6 on 2025-09-09 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='time',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
    ]
