# Generated by Django 5.2.6 on 2025-09-24 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 22, 14, 19, 636429)),
        ),
    ]
