# Generated by Django 5.2.6 on 2025-09-10 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 10, 20, 42, 53, 613556)),
        ),
    ]
