# Generated by Django 5.2.6 on 2025-09-24 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_tickets_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 24, 22, 16, 8, 449243)),
        ),
    ]
