# Generated by Django 5.2.6 on 2025-09-09 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0003_alter_tickets_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
