# Generated by Django 5.2.6 on 2025-09-09 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ticket', '0004_alter_tickets_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 9, 20, 38, 28, 145567)),
        ),
    ]
